### ISSUE TITLE
Is there any guide for installing on embedded linux?

### ISSUE THREAD

**Issue by goddade** [OHF-Voice/pymicro-wakeword#1]
II have a linux smart speaker running a variant of openwrt. musl libc. Is it possible to run pymicro_wakeword on it

**Comment by synesthesiam** [comment]
The limiting factor is going to be tensorflow. If there's a musl Python package for tensorflow, it should work.

**Comment by goddade** [comment]
Can tflite-runtime be used instead of tensorflow?

**Comment by synesthesiam** [comment]
It should work. The audio features are generated with `pymicro-features` so it should just need the TFLite interpreter.
My goal is to port this to pure C++ eventually like microVAD.

**Comment by goddade** [comment]
That's better.
